menu:
  compras:
    text: "Compras"
    url: "#"
    active_menu: :compras
    submenus:
      compras:
        text: "Compras"
        url: "#"
        active_submenu: :compras_sidemenu
      pedidos_compras:
        text: "Pedido de compras"
        url: "#"
        active_submenu: :pedidos_sidemenu
      proveedores:
        text: "Proveedores"
        url: :proveedores
        active_submenu: :proveedores_sidemenu
  ventas:
    text: "Ventas"
    url: "#"
    active_menu: :ventas
    submenus:
  stock:
    text: "Stock"
    url: "#"
    active_menu: :stock
    submenus:
      inventario:
        text: "Inventario"
        url: "#"
        active_submenu: :inventario_sidemenu
      mercaderias:
        text: "Mercaderias"
        url: :mercaderias
        active_submenu: :mercaderias_sidemenu
      movimientos_inventario:
        text: "Movimientos de mercaderias"
        url: :movimiento_mercaderias
        active_submenu: :movimientos_mercaderias_sidemenu
  cajas:
    text: "Cajas"
    url: "#"
    active_menu: :cajas
    submenus:
  reportes:
    text: "Reportes"
    url: "#"
    active_menu: :reportes
    submenus:
  configuraciones:
    text: "Configuraciones"
    url: "#"
    active_menu: :configuraciones
    submenus: