menu:
  compras:
    text: "Compras"
    url: "#"
    active_menu: :compras
    submenus:
      compras:
        text: "Compras"
        url: "#"
        active_submenu: :compras_sidemenu
      pedidos_compras:
        text: "Pedido de compras"
        url: "#"
        active_submenu: :pedidos_sidemenu
      proveedores:
        text: "Proveedores"
        url: :proveedores
        active_submenu: :proveedores_sidemenu
  ventas:
    text: "Ventas"
    url: "#"
    active_menu: :ventas
    submenus:
  stock:
    text: "Stock"
    url: :inventarios
    active_menu: :stock
    submenus:
      inventario:
        text: "Inventario"
        url: :inventarios
        active_submenu: :inventario_sidemenu
      mercaderias:
        text: "Mercaderias"
        url: :mercaderias
        active_submenu: :mercaderias_sidemenu
      movimientos_inventario:
        text: "Movimientos de inventario"
        url: "#"
        active_submenu: :movimientos_inventario_sidemenu
  cajas:
    text: "Cajas"
    url: "#"
    active_menu: :cajas
    submenus:
      cotizacion:
        text: "Cotizacion"
        url: :monedas
        active_submenu: :monedas_sidemenu
  reportes:
    text: "Reportes"
    url: "#"
    active_menu: :reportes
    submenus:
  configuraciones:
    text: "Configuraciones"
    url: "#"
    active_menu: :configuraciones
    submenus:
      datos_empresa:
        text: "Datos de la empresa"
        url: "#"
        active_submenu: :datos_empresa_sidemenu
      empleados:
        text: "Empleados"
        url: :empleados
        active_submenu: :empleados_sidemenu
