menu:
  compras:
    text: "Compras"
    url: "#"
    active_menu: :compras
    submenus:
      compras:
        text: "Compras"
        url: :compras
        active_submenu: :compras_sidemenu
      pagos:
        text: "Pagos"
        url: :pagos
        active_submenu: :pagos_sidemenu
      proveedores:
        text: "Proveedores"
        url: :proveedores
        active_submenu: :proveedores_sidemenu
      cuentas_corrientes:
        text: "Cuentas corrientes"
        url: :cuentas_corrientes_proveedores
        active_submenu: :cuentas_corrientes_proveedores
      devolucion_compras:
        text: "Devoluciones"
        url: :devolucion_compras
        active_submenu: :devolucion_compras_sidemenu
  ventas:
    text: "Ventas"
    url: :clientes
    active_menu: :ventas
    submenus:
      ventas:
        text: "Ventas"
        url: :ventas
        active_submenu: :ventas_sidemenu
      cobros:
        text: "Cobros"
        url: :cobros
        active_submenu: :cobros_sidemenu
      clientes:
        text: "Clientes"
        url: :clientes
        active_submenu: :clientes_sidemenu
      cuentas_corrientes:
        text: "Cuentas corrientes"
        url: :cuentas_corrientes_clientes
        active_submenu: :cuentas_corrientes_clientes
      devolucion_ventas:
        text: "Devoluciones"
        url: :devolucion_ventas
        active_submenu: :devolucion_ventas_sidemenu
  stock:
    text: "Stock"
    url: :inventarios
    active_menu: :stock
    submenus:
      inventario:
        text: "Inventario"
        url: :inventarios
        active_submenu: :inventario_sidemenu
      mercaderias:
        text: "Mercaderias"
        url: :mercaderias
        active_submenu: :mercaderias_sidemenu
      movimientos_inventario:
        text: "Movimientos de mercaderias"
        url: :movimiento_mercaderias
        active_submenu: :movimientos_mercaderias_sidemenu
      historico:
        text: "Histórico de mercaderias"
        url: :mercaderias_historico
        active_submenu: :mercaderias_historico
  cajas:
    text: "Cajas"
    url: "#"
    active_menu: :cajas
    submenus:
      cotizacion:
        text: "Cotizacion"
        url: :monedas
        active_submenu: :monedas_sidemenu
      categoria_gastos:
        text: "Categoria de Gastos"
        url: :categoria_gastos
        active_submenu: :categoria_gastos_sidemenu
      caja_movimientos:
        text: "Movimientos de cajas"
        url: :caja_movimientos
        active_submenu: :caja_movimientos_sidemenu
      transferencias:
        text: "Transferencias"
        url: "transferencias/new"
        active_submenu: :transferencias_sidemenu
  reportes:
    text: "Reportes"
    url: "#"
    active_menu: :reportes
    submenus:
      reporte_compras:
        text: "Reporte de compras"
        url: :reportes_compras
        active_submenu: :reporte_compras
      reporte_ventas:
        text: "Reporte de ventas"
        url: :reportes_ventas
        active_submenu: :reporte_ventas
      reporte_gastos:
        text: "Reporte de gastos"
        url: :reportes_gastos
        active_submenu: :reporte_gastos
      reporte_caja:
        text: "Reporte de caja"
        url: :reportes_caja
        active_submenu: :reporte_caja
  configuraciones:
    text: "Configuraciones"
    url: :configuraciones
    active_menu: :configuraciones
    submenus:
      datos_empresa:
        text: "Datos de la empresa"
        url: :configuraciones
        active_submenu: :datos_empresa_sidemenu
      empleados:
        text: "Usuarios"
        url: :empleados
        active_submenu: :empleados_sidemenu
