menu:
  compras:
    text: "Compras"
    url: "#"
    active_menu: :compras
    submenus:
      compras:
        text: "Compras"
        url: "#"
        active_submenu: :compras_sidemenu
      pedidos_compras:
        text: "Pedido de compras"
        url: "#"
        active_submenu: :pedidos_sidemenu
      proveedores:
        text: "Proveedores"
        url: :proveedores
        active_submenu: :proveedores_sidemenu
  ventas:
    text: "Ventas"
    url: "#"
    active_menu: :ventas
  stock:
    text: "Stock"
    url: "#"
    active_menu: :stock
  cajas:
    text: "Cajas"
    url: "#"
    active_menu: :cajas
  reportes:
    text: "Reportes"
    url: "#"
    active_menu: :reportes
  configuraciones:
    text: "Configuraciones"
    url: "#"
    active_menu: :configuraciones