# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b129d61b3c36cd917df0e3c66fa158039438d9d4a22180738e444aa68bb8fb105988a19b1fbde454adba8d0b75e087d3bcf7af0c131c1cccc07debedb7240c8

test:
  secret_key_base: 41adeca23155973b353041d97cd9ee145e49d1c2ab4babcf3caae5836939671ba58e23ffb3734bec1f2b959ee5bcadf11c48b763c4313397105ec413e177a05f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  db_name: <%= ENV["DB_NAME"] %>
  db_username: <%= ENV["DB_USERNAME"] %>
  db_password: <%= ENV["DB_PASSWORD"] %>
  db_host: <%= ENV["DB_HOST"] %>
